name: Tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - '.github/ci/Dockerfile'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}-ci:php-${{ matrix.php }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        php: ['8.3', '8.4']
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List installed dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci
